def custom_error(file, function, reason):
    print("Error\nIn file : ",file, "\nIn function : ",function,"\n",
          reason)
    exit()
